Repository anifriends/frontend, pull requests merged in 2023-11, with the labels that each got.

#13 chore : msw 의존성 및 설정 추가 및 변경
  .husky/pre-push
  .vscode/settings.json
  apps/shelter/package.json
  apps/shelter/public/mockServiceWorker.js
  apps/shelter/src/main.tsx
  apps/shelter/src/mocks/browser.ts
  apps/shelter/src/mocks/handlers.ts
  packages/eslint-config-custom/index.js
  packages/eslint-config-custom/package.json
  packages/tsconfig/package.json
  pnpm-lock.yaml
Labels: 🏅 Chore, 🔥 Must have

#15 chore : vite 절대경로 설정
  .lintstagedrc
  apps/shelter/package.json
  apps/shelter/tsconfig.json
  apps/shelter/vite.config.ts
  apps/volunteer/package.json
  apps/volunteer/tsconfig.json
  apps/volunteer/vite.config.ts
  pnpm-lock.yaml
Labels: 🏅 Chore, 🧊 Nice to have

#27 feat: Label, LabelText 공통 컴포넌트
  packages/ui/components/Label.tsx
  packages/ui/components/LabetText.tsx
Labels: 🐣 Feat

#29 feat: 공용 레이아웃 컴포넌트 추가
  apps/shelter/src/components/layout/index.tsx
  apps/shelter/src/routes/index.tsx
  apps/volunteer/src/components/layout/index.tsx
  apps/volunteer/src/routes/index.tsx
  packages/ui/assets/icon_back.svg
  packages/ui/assets/icon_menu.svg
  packages/ui/assets/icon_notifications.svg
  packages/ui/assets/icon_search.svg
  packages/ui/assets/icon_settings.svg
  packages/ui/constants/appType.ts
  packages/ui/constants/headerType.ts
  packages/ui/constants/pageType.ts
  packages/ui/layout/BottomNavBar/index.tsx
  packages/ui/layout/Header/DefaultHeader.tsx
  packages/ui/layout/Header/DetailHeader.tsx
  packages/ui/layout/Header/SearchHeader.tsx
  packages/ui/layout/Header/index.tsx
  packages/ui/layout/Header/useHeader.ts
  packages/ui/layout/Header/utils.ts
  packages/ui/layout/index.tsx
  packages/ui/package.json
  packages/ui/svg.d.ts
  packages/ui/tsconfig.json
  packages/ui/types/app.ts
  packages/ui/types/header.ts
  packages/ui/types/page.ts
  pnpm-lock.yaml
Labels: 🐣 Feat

#36 fix : vercel 배포 링크에서 라우팅 오류 해결
  apps/shelter/vercel.json
  apps/volunteer/vercel.json
Labels: 🔨 Fix

#34 feat: BottomNavBar 컴포넌트 개발
  apps/shelter/src/components/layout/index.tsx
  apps/volunteer/src/components/layout/index.tsx
  packages/ui/assets/bottomNavBar/icon_animals_selected.svg
  packages/ui/assets/bottomNavBar/icon_animals_unselected.svg
  packages/ui/assets/bottomNavBar/icon_chattings_selected.svg
  packages/ui/assets/bottomNavBar/icon_chattings_unselected.svg
  packages/ui/assets/bottomNavBar/icon_mypage_selected.svg
  packages/ui/assets/bottomNavBar/icon_mypage_unselected.svg
  packages/ui/assets/bottomNavBar/icon_volunteers_selected.svg
  packages/ui/assets/bottomNavBar/icon_volunteers_unselected.svg
  packages/ui/layout/BottomNavBar/NavBarButton.tsx
  packages/ui/layout/BottomNavBar/index.tsx
  packages/ui/layout/BottomNavBar/useBottomNavBar.ts
Labels: 🐣 Feat

#38 feat: InfoTextList, InfoTextItem 컴포넌트 추가 및 DateText 컴포넌트 제거
  apps/shelter/src/App.tsx
  apps/volunteer/src/App.tsx
  commitlint.config.js
  packages/ui/components/InfoTextItem.tsx
  packages/ui/components/InfoTextList.tsx
  packages/ui/components/LabelText.tsx
Labels: 🐣 Feat, ✂️ Remove, 🛠 Refactor

#31 feat(ui): profileInfo 컴포넌트 제작
  packages/ui/components/ProfileInfo.tsx
Labels: 🐣 Feat

#39 chore: packages의 ui를 shared로 변경, library 버전 통일, router 타입 추가
  .eslintrc.js
  apps/shelter/package.json
  apps/shelter/src/components/layout/index.tsx
  apps/shelter/src/routes/index.tsx
  apps/volunteer/package.json
  apps/volunteer/src/components/layout/index.tsx
  apps/volunteer/src/routes/index.tsx
  cz-config.js
  package.json
  packages/shared/.eslintrc.cjs
  packages/shared/.gitignore
  packages/shared/assets/bottomNavBar/icon_animals_selected.svg
  packages/shared/assets/bottomNavBar/icon_animals_unselected.svg
  packages/shared/assets/bottomNavBar/icon_chattings_selected.svg
  packages/shared/assets/bottomNavBar/icon_chattings_unselected.svg
  packages/shared/assets/bottomNavBar/icon_mypage_selected.svg
  packages/shared/assets/bottomNavBar/icon_mypage_unselected.svg
  packages/shared/assets/bottomNavBar/icon_volunteers_selected.svg
  packages/shared/assets/bottomNavBar/icon_volunteers_unselected.svg
  packages/shared/assets/icon_back.svg
  packages/shared/assets/icon_menu.svg
  packages/shared/assets/icon_notifications.svg
  packages/shared/assets/icon_search.svg
  packages/shared/assets/icon_settings.svg
  packages/shared/components/CustomButton.tsx
  packages/shared/components/Header.tsx
  packages/shared/components/InfoTextItem.tsx
  packages/shared/components/InfoTextList.tsx
  packages/shared/components/Label.tsx
  packages/shared/components/LabelText.tsx
  packages/shared/components/ProfileInfo.tsx
  packages/shared/constants/appType.ts
  packages/shared/constants/headerType.ts
  packages/shared/constants/pageType.ts
  packages/shared/index.tsx
  packages/shared/layout/BottomNavBar/NavBarButton.tsx
  packages/shared/layout/BottomNavBar/index.tsx
  packages/shared/layout/BottomNavBar/useBottomNavBar.ts
  packages/shared/layout/Header/DefaultHeader.tsx
  packages/shared/layout/Header/DetailHeader.tsx
  packages/shared/layout/Header/SearchHeader.tsx
  packages/shared/layout/Header/index.tsx
  packages/shared/layout/Header/useHeader.ts
  packages/shared/layout/Header/utils.ts
  packages/shared/package.json
  packages/shared/svg.d.ts
  packages/shared/tsconfig.json
  packages/shared/types/app.ts
  packages/shared/types/header.ts
  packages/shared/types/page.ts
  packlint.config.mjs
  pnpm-lock.yaml
Labels: 🏅 Chore, 🔥 Must have, 🔨 Fix

#40 feat: axios Interceptor 추가
  packages/shared/api/axiosInstance.ts
  packages/shared/api/axiosInterceptor.ts
  packages/shared/constants/baseURL.ts
  packages/shared/package.json
  pnpm-lock.yaml
Labels: 🐣 Feat

#42 fix(shared): 단위를 %에서 rem, calc를 활용하여 변경
  packages/shared/components/InfoTextList.tsx
Labels: 🧊 Nice to have, 🔨 Fix

#44 feat: ApplicantStatus 컴포넌트 개발
  packages/shared/assets/icon_applicant.svg
  packages/shared/components/ApplicantStatus.tsx
Labels: 🐣 Feat

#48 fix: 공통 레이아웃 컴포넌트 margin 버그 수정 및 리팩토링
  apps/shelter/src/components/layout/index.tsx
  apps/shelter/src/routes/index.tsx
  apps/volunteer/src/components/layout/index.tsx
  apps/volunteer/src/routes/index.tsx
  packages/shared/layout/index.tsx
  packages/shared/types/header.ts
Labels: 🐛 Bug

#55 feat(shared): ImageCarousel 컴포넌트 추가
  packages/shared/components/ImageCarousel.tsx
Labels: 🐣 Feat, 🔥 Must have

#51 feat : ReviewItem 컴포넌트
  packages/shared/components/ReviewItem.tsx
Labels: 🐣 Feat

#52 feat: EditPhotoList, EditPhotoItem 컴포넌트 추가
  packages/shared/assets/icon_BiX.svg
  packages/shared/assets/icon_IoCamera.svg
  packages/shared/components/EditPhotoItem.tsx
  packages/shared/components/EditPhotoList.tsx
Labels: 🐣 Feat, 🔥 Must have

#46 feat: api 함수 부분적으로 추가
  packages/shared/apis/axiosInstance.ts
  packages/shared/apis/axiosInterceptor.ts
  packages/shared/apis/common/Auth.ts
  packages/shared/apis/common/Recruitments.ts
  packages/shared/apis/shelters/Recruitments.ts
  packages/shared/apis/shelters/Review.ts
  packages/shared/apis/shelters/Shelter.ts
  packages/shared/apis/volunteers/Animal.ts
  packages/shared/apis/volunteers/Recruitments.ts
  packages/shared/apis/volunteers/Review.ts
  packages/shared/apis/volunteers/Shelter.ts
  packages/shared/apis/volunteers/Volunteer.ts
Labels: 🐣 Feat

#49 feat: SettingGroup & SettingItem 컴포넌트 개발
  packages/shared/assets/icon_next.svg
  packages/shared/components/SettingGroup.tsx
  packages/shared/components/SettingItem.tsx
Labels: 🐣 Feat, 🔥 Must have

#59 feat: InfoTextItem 컴포넌트 리팩토링 및 InfoItem 컴포넌트를 통한 확장성 개선
  packages/shared/components/InfoItem.tsx
  packages/shared/components/InfoList.tsx
  packages/shared/components/InfoSubtext.tsx
  packages/shared/components/InfoTextItem.tsx
  packages/shared/components/InfoTextList.tsx
Labels: 🛠 Refactor

#68 feat: Pretendard 폰트 추가, Provider 위치 통일 및 추가
  apps/shelter/package.json
  apps/shelter/src/App.tsx
  apps/shelter/src/main.tsx
  apps/volunteer/package.json
  apps/volunteer/src/App.tsx
  packages/shared/fonts/Pretendard-Regular.woff
  packages/shared/fonts/index.tsx
  packages/shared/theme/index.ts
Labels: 🏅 Chore, 🐣 Feat, 💧 Should have

#66 feat: 보호소앱과 봉사자앱의 로그인 페이지의 UI, useToggle 훅 추가
  apps/shelter/src/pages/signin/index.tsx
  apps/volunteer/src/pages/signin/index.tsx
  packages/shared/assets/icon-IoEyeOff.svg
  packages/shared/assets/icon-IoEyeSharp.svg
  packages/shared/assets/image-anifriends-logo.png
  packages/shared/hooks/useToggle.ts
Labels: 🐣 Feat

#62 feat: 보호소 앱 마이페이지 UI 개발
  apps/shelter/src/pages/my/index.tsx
  packages/shared/components/ProfileInfo.tsx
  packages/shared/components/SettingGroup.tsx
  packages/shared/components/SettingItem.tsx
Labels: 🐣 Feat

#74 feat: 봉사 모집글 리스트 페이지 ui
  apps/shelter/src/pages/volunteers/RecruitDateText.tsx
  apps/shelter/src/pages/volunteers/RecruitItem.tsx
  apps/shelter/src/pages/volunteers/index.tsx
  apps/volunteer/src/pages/volunteers/VolunteerRecruitItem.tsx
Labels: 🐣 Feat, 🔥 Must have

#76 refactor: Signin 페이지 svg 파일 컴포넌트로 변환, useToggle initialState false로 변경
  apps/shelter/src/pages/signin/index.tsx
  apps/volunteer/src/pages/signin/index.tsx
  packages/shared/assets/IoEyeOff.tsx
  packages/shared/assets/IoEyeSharp.tsx
  packages/shared/hooks/useToggle.ts
Labels: 🔥 Must have, 🛠 Refactor

#60 feat: api 추가
  packages/shared/apis/common/Auth.ts
  packages/shared/apis/common/Image.ts
  packages/shared/apis/common/Recruitments.ts
  packages/shared/apis/common/Review.ts
  packages/shared/apis/common/Volunteer.ts
  packages/shared/apis/shelters/Recruitments.ts
  packages/shared/apis/shelters/Shelter.ts
Labels: 🐣 Feat, 🔥 Must have

#83 hotfix: api 함수 에러 해결
  apps/shelter/src/mocks/handlers/auth.ts
  apps/volunteer/src/mocks/handlers/auth.ts
  packages/shared/apis/shelters/Shelter.ts
  packages/shared/components/CustomButton.tsx
  packages/shared/components/Header.tsx
Labels: 🔥 Must have, 🔨 Fix

#86 bug: 공통 레이아웃 컴포넌트 UI 깨짐 현상 수정
  packages/shared/layout/Header/DefaultHeader/index.tsx
  packages/shared/layout/Header/DetailHeader/index.tsx
  packages/shared/layout/Header/SearchHeader/index.tsx
  packages/shared/layout/index.tsx
  packages/shared/theme/index.ts
Labels: 🔥 Must have, 🐛 Bug

#80 feat: 보호소앱과 봉사자앱의 회원가입 페이지의 UI, useRadioGroup 훅, RadioGroup 컴포넌트 추가
  apps/shelter/src/pages/signup/index.tsx
  apps/volunteer/src/pages/signup/index.tsx
  packages/shared/components/RadioGroup.tsx
  packages/shared/hooks/useRadioGroup.ts
Labels: 🐣 Feat, 🔥 Must have

#87 Refactor : shared에 있는 api들에서 공통 api들을 제외하고 각 apps의 api로 이동
  apps/shelter/src/apis/auth.ts
  apps/shelter/src/apis/recruitment.ts
  apps/shelter/src/apis/shelter.ts
  apps/volunteer/src/apis/animal.ts
  apps/volunteer/src/apis/auth.ts
  apps/volunteer/src/apis/recruitment.ts
  apps/volunteer/src/apis/review.ts
  apps/volunteer/src/apis/shelter.ts
  apps/volunteer/src/apis/volunteer.ts
  packages/shared/apis/common/Auth.ts
  packages/shared/apis/shelters/Review.ts
Labels: 🛠 Refactor

#95 design(shared): 공통 레이아웃 컴포넌트의 margin bottom 제거
  packages/shared/layout/index.tsx
Labels: 🎨 Design

#96 feat(shelter): 봉사 모집 게시글 페이지 UI 및 Filter hook 개발
  apps/shelter/src/pages/volunteers/search/_components/FilterGroup.tsx
  apps/shelter/src/pages/volunteers/search/_components/FilterSelect.tsx
  apps/shelter/src/pages/volunteers/search/_constants/filter.ts
  apps/shelter/src/pages/volunteers/search/_hooks/useSearchFilter.ts
  apps/shelter/src/pages/volunteers/search/_hooks/useVolunteerSearch.ts
  apps/shelter/src/pages/volunteers/search/_hooks/useVolunteerSearchFilter.ts
  apps/shelter/src/pages/volunteers/search/_types/filter.ts
  apps/shelter/src/pages/volunteers/search/_utils/createFilter.ts
  apps/shelter/src/pages/volunteers/search/index.tsx
  packages/shared/constants/date.ts
  packages/shared/layout/Header/SearchHeader/index.tsx
  packages/shared/utils/date.ts
Labels: 🐣 Feat

#97 feat(shelter): 보호소 마이페이지 msw 연결
  apps/shelter/src/apis/shelter.ts
  apps/shelter/src/mocks/browser.ts
  apps/shelter/src/mocks/handlers/shelter.ts
  apps/shelter/src/pages/my/_hooks/useMyPage.ts
  apps/shelter/src/pages/my/index.tsx
  apps/shelter/src/types/apis/shetler.ts
Labels: 🐣 Feat

#100 feat: 보호소앱과 봉사자앱의 로그인 페이지의 로직 추가
  apps/shelter/src/pages/signin/index.tsx
  apps/volunteer/src/pages/signin/index.tsx
Labels: 🐣 Feat, 🔥 Must have

#99 feat: 보호소앱과 봉사자앱의 회원가입 페이지의 로직 추가
  apps/shelter/src/pages/signup/index.tsx
  apps/volunteer/src/constants/gender.ts
  apps/volunteer/src/pages/signup/index.tsx
  apps/volunteer/src/types/gender.ts
Labels: 🐣 Feat, 🔥 Must have

#91 feat(shelter): 무한 스크롤 훅 추가
  apps/shelter/src/pages/volunteers/hooks/useIntersection.tsx
Labels: 🐣 Feat

#105 feat: 보호소 봉사모집 상세페에지 UI 및 버튼 로직 구현
  apps/shelter/src/pages/volunteers/detail/AlertModal.tsx
  apps/shelter/src/pages/volunteers/detail/index.tsx
  packages/shared/components/InfoTextList.tsx
Labels: 🐣 Feat, 🔥 Must have

#108 feat: 보호소 리뷰 페이지에 api 연결 및 로직 추가
  apps/shelter/src/apis/recruitment.ts
  apps/shelter/src/apis/shelter.ts
  apps/shelter/src/hooks/useIntersection.tsx
  apps/shelter/src/mocks/handlers/shelter.ts
  apps/shelter/src/pages/my/reviews/hooks/useFetchShelterReviews.tsx
  apps/shelter/src/pages/my/reviews/index.tsx
  apps/shelter/src/pages/volunteers/index.tsx
  packages/shared/utils/date.ts
Labels: 🐣 Feat

#114 feat: 보호소앱, 봉사자앱의 auth(signin, signup) api, api 관련 type, msw handler 추가
  apps/shelter/src/apis/auth.ts
  apps/shelter/src/mocks/handlers/auth.ts
  apps/shelter/src/types/apis/auth.ts
  apps/volunteer/src/apis/auth.ts
  apps/volunteer/src/mocks/handlers/auth.ts
  apps/volunteer/src/types/apis/auth.ts
  packages/shared/types/apis/auth.ts
  packages/shared/types/apis/error.ts
Labels: 🐣 Feat, 🔥 Must have

#116 feat: Pretendard에서 IBM Plex Sans으로 기본 폰트 변경
  packages/shared/fonts/IBMPlexSans-Regular.woff
  packages/shared/fonts/Pretendard-Regular.woff
  packages/shared/fonts/index.tsx
  packages/shared/theme/index.ts
Labels: 🐣 Feat, 💧 Should have

#118 refactor: auth 관련 타입 상수명 개선 및 tanstack react query 사용으로 인한 auth api 내부 try catch (error) 제거
  apps/shelter/src/apis/auth.ts
  apps/shelter/src/types/apis/auth.ts
  apps/volunteer/src/apis/auth.ts
  apps/volunteer/src/types/apis/auth.ts
  packages/shared/types/apis/auth.ts
  packages/shared/types/apis/error.ts
Labels: 🔥 Must have, 🛠 Refactor

#119 feat(shelter, volunteer): SigninPage 컴포넌트 msw 관련 로직 추가
  apps/shelter/src/pages/signin/index.tsx
  apps/volunteer/src/pages/signin/index.tsx
Labels: 🐣 Feat, 🔥 Must have

#124 feat: 보호소앱과 봉사자앱의 회원가입 페이지의 msw 연동 및 관련 로직 추가
  apps/shelter/src/apis/auth.ts
  apps/shelter/src/pages/signup/index.tsx
  apps/volunteer/src/apis/auth.ts
  apps/volunteer/src/pages/signup/index.tsx
  packages/shared/types/apis/auth.ts
Labels: 🐣 Feat, 🔥 Must have, 🛠 Refactor

#123 Feat: 봉사모집 상세페이지 msw 연결
  apps/shelter/src/mocks/browser.ts
  apps/shelter/src/mocks/handlers/recruitmentDetail.ts
  apps/shelter/src/pages/volunteers/detail/_hooks/useGetVolunteerDetail.ts
  apps/shelter/src/pages/volunteers/detail/index.tsx
  packages/shared/components/LabelText.tsx
  packages/shared/constants/date.ts
  packages/shared/utils/date.ts
Labels: 🐣 Feat

#130 feat: 봉사자 리스트 페이지에 플로팅 버튼 추가
  apps/shelter/src/pages/volunteers/_components/PlusIcon.tsx
  apps/shelter/src/pages/volunteers/index.tsx
  packages/shared/apis/axiosInstance.ts
Labels: 🐣 Feat

#134 refactor: @tanstack/react-query의 기본 Error 타입 AxiosError로 변경
  apps/shelter/src/pages/signin/index.tsx
  apps/shelter/src/pages/signup/index.tsx
  apps/shelter/src/react-query.d.ts
  apps/volunteer/src/pages/signin/index.tsx
  apps/volunteer/src/pages/signup/index.tsx
  apps/volunteer/src/react-query.d.ts
Labels: 💧 Should have, 🛠 Refactor

#131 feat: 계정 수정 페이지 UI (봉사자, 보호소)
  apps/shelter/src/pages/settings/account/index.tsx
  apps/volunteer/src/pages/settings/account/index.tsx
  apps/volunteer/src/routes/index.tsx
Labels: 🐣 Feat

#136 feat(shelter): 봉사 모집 검색 페이지 필터 로직 수정 및 코드 개선
  apps/shelter/src/pages/volunteers/search/_constants/filter.ts
  apps/shelter/src/pages/volunteers/search/_hooks/useSearchFilter.ts
  apps/shelter/src/pages/volunteers/search/_hooks/useVolunteerSearch.ts
  apps/shelter/src/pages/volunteers/search/_hooks/useVolunteerSearchFilter.ts
  apps/shelter/src/pages/volunteers/search/_types/filter.ts
  apps/shelter/src/pages/volunteers/search/_utils/createFilter.ts
  apps/shelter/src/pages/volunteers/search/index.tsx
Labels: 🐣 Feat

#135 feat : 봉사자 출석 관리 페이지 ui
  apps/shelter/src/pages/manage/attendance/index.tsx
Labels: 🐣 Feat

#138 feat: 보호소앱, 봉사자앱 비밀번호 변경 페이지 UI 및 로직 추가
  apps/shelter/src/pages/settings/password/index.tsx
  apps/volunteer/src/pages/settings/password/index.tsx
  packages/shared/components/LogoImageBox.tsx
  packages/shared/png.d.ts
Labels: 🐣 Feat, 🔥 Must have

#146 feat(shelter): 봉사자 모집 검색 페이지 msw 연결
  apps/shelter/src/apis/recruitment.ts
  apps/shelter/src/pages/volunteers/_queryOptions/recruitment.ts
  apps/shelter/src/pages/volunteers/hooks/useFetchVolunteers.tsx
  apps/shelter/src/pages/volunteers/index.tsx
  apps/shelter/src/pages/volunteers/search/_components/RecruitmentsSearchFilter.tsx
  apps/shelter/src/pages/volunteers/search/_constants/filter.ts
  apps/shelter/src/pages/volunteers/search/_utils/period.ts
  apps/shelter/src/pages/volunteers/search/index.tsx
  apps/shelter/src/types/apis/recruitment.ts
Labels: 🐣 Feat

#148 feat(volunteer): 봉사자 모집 게시글 리스트 UI 개발
  apps/volunteer/src/pages/volunteers/VolunteerRecruitItem.tsx
  apps/volunteer/src/pages/volunteers/_components/VolunteerRecruitItem.tsx
  apps/volunteer/src/pages/volunteers/index.tsx
  packages/shared/components/ApplicantStatus.tsx
  packages/shared/components/InfoSubtext.tsx
  packages/shared/components/Label.tsx
  packages/shared/components/LabelText.tsx
Labels: 🐣 Feat, 🔥 Must have

#142 feat(shelter): 봉사자 모집글 추가 페이지 ui 추가
  apps/shelter/src/pages/volunteers/write/index.tsx
Labels: 🐣 Feat, 🔥 Must have

#147 feat: 봉사자앱 봉사 모집 상세 페이지 UI 개발
  apps/shelter/src/pages/volunteers/detail/index.tsx
  apps/volunteer/src/constants/path.ts
  apps/volunteer/src/pages/volunteers/detail/index.tsx
  packages/shared/components/AlertModal.tsx
Labels: 🐣 Feat

#156 feat: 보호소앱 봉사 신청 현황 페이지 UI 추가 및 gender, applicant 관련 type 공통화, 정리
  apps/shelter/src/assets/CkCheck.tsx
  apps/shelter/src/constants/recruitment.ts
  apps/shelter/src/pages/manage/apply/_components/ApplyInfoItem.tsx
  apps/shelter/src/pages/manage/apply/_components/ApprovedCountBox.tsx
  apps/shelter/src/pages/manage/apply/_components/ManageApplyItem.tsx
  apps/shelter/src/pages/manage/apply/index.tsx
  apps/shelter/src/types/apis/recruitment.ts
  apps/shelter/src/types/recruitment.ts
  apps/volunteer/src/pages/signup/index.tsx
  apps/volunteer/src/types/apis/auth.ts
  apps/volunteer/src/types/gender.ts
  packages/shared/constants/gender.ts
  packages/shared/types/gender.ts
  packages/shared/utils/date.ts
Labels: 🐣 Feat, 🔥 Must have

#158 refactor(shared): IBMPlexSans 폰트 cdn 웹폰트로 변경
  apps/shelter/index.html
  apps/volunteer/index.html
  packages/shared/fonts/IBMPlexSans-Regular.woff
  packages/shared/fonts/index.tsx
Labels: 🐣 Feat, 🧊 Nice to have, 🔨 Fix, 🛠 Refactor

#162 feat(volunteer): 봉사 모집 게시글 msw 연결 및 무한 스크롤 기능 추가
  apps/shelter/src/pages/my/reviews/index.tsx
  apps/shelter/src/pages/volunteers/index.tsx
  apps/shelter/src/pages/volunteers/search/index.tsx
  apps/volunteer/src/apis/recruitment.ts
  apps/volunteer/src/mocks/browser.ts
  apps/volunteer/src/mocks/handlers/recruitment.ts
  apps/volunteer/src/pages/volunteers/_queryOptions/recruitments.ts
  apps/volunteer/src/pages/volunteers/index.tsx
  apps/volunteer/src/types/apis/recruitment.ts
  packages/shared/hooks/useIntersection.tsx
Labels: 🐣 Feat

#160 feat : 보호소 출석관리 페이지에 로직 추가
  apps/shelter/src/apis/recruitment.ts
  apps/shelter/src/mocks/browser.ts
  apps/shelter/src/mocks/handlers/manage.ts
  apps/shelter/src/pages/manage/attendance/index.tsx
  apps/shelter/src/types/apis/recruitment.ts
Labels: 🐣 Feat

#164 feat(volunteer): 봉사모집글 검색 페이지 msw 연결 및 무한 스크롤 기능 추가
  apps/shelter/src/pages/volunteers/search/_components/RecruitmentsSearchFilter.tsx
  apps/shelter/src/pages/volunteers/search/_constants/filter.ts
  apps/shelter/src/pages/volunteers/search/_types/filter.ts
  apps/shelter/src/pages/volunteers/search/index.tsx
  apps/volunteer/src/pages/volunteers/_components/VolunteerRecruitItem.tsx
  apps/volunteer/src/pages/volunteers/_utils/recruitment.ts
  apps/volunteer/src/pages/volunteers/index.tsx
  apps/volunteer/src/pages/volunteers/search/_components/RecruitmentsSearchFilter.tsx
  apps/volunteer/src/pages/volunteers/search/_constants/filter.ts
  apps/volunteer/src/pages/volunteers/search/_types/filter.ts
  apps/volunteer/src/pages/volunteers/search/index.tsx
  apps/volunteer/src/types/apis/recruitment.ts
  packages/shared/constants/period.ts
  packages/shared/types/period.ts
  packages/shared/utils/period.ts
Labels: 🐣 Feat

#171 feat(shared): Tabs 공통 컴포넌트 추가
  packages/shared/components/Tabs.tsx
Labels: 🐣 Feat, 💧 Should have

#180 feat: 봉사자앱 보호소프로필 페이지 UI 개발
  apps/volunteer/src/pages/shelters/profile/_components/ShelterRecruitments.tsx
  apps/volunteer/src/pages/shelters/profile/_components/ShelterReviews.tsx
  apps/volunteer/src/pages/shelters/profile/index.tsx
Labels: 🐣 Feat

#182 feat(shared): Tabs 컴포넌트 내부 배경 색상 추가
  packages/shared/components/Tabs.tsx
Labels: 🐣 Feat, 🔥 Must have

#179 fix(shared): font의 고정된 fontWeight 제거
  packages/shared/fonts/index.tsx
Labels: 🔨 Fix

#177 feat(volunteer): 봉사자 어플 세팅 페이지 추가
  apps/volunteer/src/pages/settings/index.tsx
  apps/volunteer/src/routes/index.tsx
Labels: 🐣 Feat

#184 chore(shared): baseUrl 설정
  package.json
  packages/shared/constants/baseURL.ts
  pnpm-lock.yaml
  turbo.json
Labels: 🏅 Chore, 🐣 Feat

#188 feat: zod 유효성 검사 항목들 공통화
  packages/shared/package.json
  packages/shared/utils/validations.ts
  pnpm-lock.yaml
Labels: 🏅 Chore, 🐣 Feat, 💧 Should have

#189 feat: Local ErrorBoundary 및 Global ErrorBoundary 추가
  packages/shared/apis/axiosInterceptor.ts
  packages/shared/components/LocalErrorBoundary.tsx
  packages/shared/package.json
  pnpm-lock.yaml
Labels: 🐣 Feat

#167 feat: 계정정보수정 (봉사자, 보호소) msw 연결
  apps/shelter/src/apis/shelter.ts
  apps/shelter/src/mocks/handlers/shelter.ts
  apps/shelter/src/pages/settings/account/_hooks/useFetchShelterAccount.ts
  apps/shelter/src/pages/settings/account/index.tsx
  apps/shelter/src/types/apis/shetler.ts
  apps/volunteer/src/apis/volunteer.ts
  apps/volunteer/src/mocks/browser.ts
  apps/volunteer/src/mocks/handlers/volunteer.ts
  apps/volunteer/src/pages/settings/account/_hooks/useFetchAccount.ts
  apps/volunteer/src/pages/settings/account/index.tsx
Labels: 🐣 Feat

#191 feat(shared): EditPhotoList 컴포넌트의 비즈니스 로직을 hook 으로 분리 및 리팩토링
  apps/shelter/src/pages/volunteers/update/index.tsx
  apps/shelter/src/pages/volunteers/write/index.tsx
  packages/shared/apis/common/Image.ts
  packages/shared/components/EditPhotoItem.tsx
  packages/shared/components/EditPhotoList.tsx
  packages/shared/hooks/useUploadPhoto.ts
Labels: 🐣 Feat

#196 feat(volunteer): 봉사 후기 작성 및 수정 페이지 라우팅 수정
  apps/volunteer/src/constants/path.ts
  apps/volunteer/src/pages/shelters/reviews/update/index.tsx
  apps/volunteer/src/pages/shelters/reviews/write/index.tsx
Labels: 🐣 Feat

#201 feat(shared): heading, body font를 font-weight 제거, theme의 font IBMPlexSans로 통일 후 적용
  packages/shared/fonts/index.tsx
  packages/shared/theme/index.ts
Labels: 🐣 Feat, 💧 Should have

#206 feat: 보호소의 봉사자 프로필 페이지 UI 추가
  apps/shelter/src/constants/path.ts
  apps/shelter/src/pages/volunteers/profile/_components/VolunteerRecords.tsx
  apps/shelter/src/pages/volunteers/profile/_components/VolunteerReviews.tsx
  apps/shelter/src/pages/volunteers/profile/index.tsx
  packages/shared/components/Tabs.tsx
Labels: 🐣 Feat, 🔥 Must have

#211 feat(volunteer): 봉사 후기 작성 및 수정 페이지 UI 개발
  apps/volunteer/src/pages/shelters/reviews/_components/ReviewSubmitButton.tsx
  apps/volunteer/src/pages/shelters/reviews/_constants/reviews.ts
  apps/volunteer/src/pages/shelters/reviews/_schema/reviewSchema.ts
  apps/volunteer/src/pages/shelters/reviews/update/index.tsx
  apps/volunteer/src/pages/shelters/reviews/write/index.tsx
Labels: 🐣 Feat

#210 feat: 모집 리스트 스켈레톤
  apps/shelter/src/pages/volunteers/_components/RecruitSkeleton.tsx
  apps/shelter/src/pages/volunteers/_components/RecruitSkeletonList.tsx
  apps/shelter/src/pages/volunteers/index.tsx
  apps/shelter/src/pages/volunteers/search/index.tsx
  apps/volunteer/src/mocks/handlers/recruitment.ts
  apps/volunteer/src/pages/volunteers/_components/RecruitSkeleton.tsx
  apps/volunteer/src/pages/volunteers/_components/RecruitSkeletonList.tsx
  apps/volunteer/src/pages/volunteers/index.tsx
  apps/volunteer/src/pages/volunteers/search/index.tsx
Labels: 🐣 Feat

#209 refactor: 공통화로 묶은 zod validation로 기존 페이지들(Signin, Sigup, SettingsPassword) 변경
  apps/shelter/src/pages/settings/password/index.tsx
  apps/shelter/src/pages/signin/index.tsx
  apps/shelter/src/pages/signup/index.tsx
  apps/volunteer/src/pages/settings/password/index.tsx
  apps/volunteer/src/pages/signin/index.tsx
  apps/volunteer/src/pages/signup/index.tsx
  packages/shared/utils/validations.ts
Labels: 💧 Should have, 🔨 Fix, 🛠 Refactor

#221 feat: 봉사모집 상세조회 useQuery hook 리팩토링
  apps/shelter/src/pages/volunteers/detail/_hooks/useGetVolunteerDetail.ts
  apps/shelter/src/pages/volunteers/detail/index.tsx
  apps/shelter/src/pages/volunteers/update/index.tsx
  packages/shared/apis/common/Recruitments.ts
Labels: 🛠 Refactor

#217 feat: 봉사자앱의 보호소프로필 페이지 msw 연결
  apps/volunteer/src/apis/review.ts
  apps/volunteer/src/apis/shelter.ts
  apps/volunteer/src/mocks/handlers/shelter.ts
  apps/volunteer/src/pages/shelters/profile/_components/ShelterRecruitments.tsx
  apps/volunteer/src/pages/shelters/profile/_components/ShelterReviews.tsx
  apps/volunteer/src/pages/shelters/profile/index.tsx
Labels: 🐣 Feat

#216 feat: 보호소의 봉사자 프로필 페이지 api를 포함한 로직 추가
  apps/shelter/src/apis/volunteers.ts
  apps/shelter/src/mocks/browser.ts
  apps/shelter/src/mocks/handlers/volunteers.ts
  apps/shelter/src/pages/volunteers/profile/_components/VolunteerRecords.tsx
  apps/shelter/src/pages/volunteers/profile/_components/VolunteerRecruitments.tsx
  apps/shelter/src/pages/volunteers/profile/_components/VolunteerReviews.tsx
  apps/shelter/src/pages/volunteers/profile/index.tsx
  apps/shelter/src/types/apis/volunteers.ts
Labels: 🐣 Feat, 🔥 Must have

#218 feat: 봉사자앱의 마이페이지 UI, msw 연결
  apps/volunteer/src/apis/volunteer.ts
  apps/volunteer/src/pages/my/_hooks/useFetchMyVolunteer.ts
  apps/volunteer/src/pages/my/index.tsx
  apps/volunteer/src/pages/settings/account/_hooks/useFetchAccount.ts
  apps/volunteer/src/pages/settings/account/index.tsx
Labels: 🐣 Feat

#165 feat: 보호소앱 봉사 신청 현황 페이지 msw(api), 로직 추가
  apps/shelter/src/assets/CkClose.tsx
  apps/shelter/src/constants/recruitment.ts
  apps/shelter/src/mocks/handlers/recruitment.ts
  apps/shelter/src/pages/manage/apply/_components/ApplyInfoItem.tsx
  apps/shelter/src/pages/manage/apply/_components/ApprovedCountBox.tsx
  apps/shelter/src/pages/manage/apply/_components/ManageApplyItem.tsx
  apps/shelter/src/pages/manage/apply/index.tsx
  apps/shelter/src/types/apis/recruitment.ts
Labels: 🐣 Feat, 🔥 Must have

#222 feat(volunteer): 봉사자 앱 리뷰 작성 및 수정 페이지 msw 연결
  apps/volunteer/src/apis/review.ts
  apps/volunteer/src/apis/shelter.ts
  apps/volunteer/src/mocks/browser.ts
  apps/volunteer/src/mocks/handlers/image.ts
  apps/volunteer/src/mocks/handlers/review.ts
  apps/volunteer/src/pages/shelters/profile/_components/ShelterReviews.tsx
  apps/volunteer/src/pages/shelters/reviews/_components/ReviewSubmitButton.tsx
  apps/volunteer/src/pages/shelters/reviews/_constants/reviews.ts
  apps/volunteer/src/pages/shelters/reviews/_schema/reviewSchema.ts
  apps/volunteer/src/pages/shelters/reviews/update/index.tsx
  apps/volunteer/src/pages/shelters/reviews/write/index.tsx
  apps/volunteer/src/types/apis/review.ts
  packages/shared/apis/axiosInstance.ts
  packages/shared/apis/common/Image.ts
  packages/shared/hooks/useUploadPhoto.ts
Labels: 🐣 Feat

#225 feat(shelter): 봉사 모집 게시글 작성 및 수정 페이지 form 제출 시, request 에 이미지 url 추가
  apps/shelter/src/pages/volunteers/update/index.tsx
  apps/shelter/src/pages/volunteers/write/index.tsx
Labels: 🐣 Feat

#199 feat : 에러바운더리 기능 추가 및 적용
  packages/shared/components/LocalErrorBoundary.tsx
  packages/shared/layout/index.tsx
  packages/shared/utils/errorMessage.ts
Labels: 🐣 Feat

#229 feat(volunteer): 봉사 후기 수정 페이지 진입 시, 기존 데이터 form 에 넣어주는 기능 추가 및 msw 연결
  apps/volunteer/src/apis/review.ts
  apps/volunteer/src/mocks/handlers/review.ts
  apps/volunteer/src/pages/shelters/reviews/update/index.tsx
  apps/volunteer/src/types/apis/review.ts
  packages/shared/hooks/useUploadPhoto.ts
Labels: 🐣 Feat

#235 fix(shared): global theme의 overscroll-behavior css 속성을 카멜 케이스로 수정
  packages/shared/theme/index.ts
Labels: 🐣 Feat

#232 feat(shelter): 봉사자 모집글 리스트에서 아이템 변경시, 캐싱된 서버 상테 업데이트하는 기능 추가
  apps/shelter/src/mocks/handlers/recruitment.ts
  apps/shelter/src/pages/volunteers/_hooks/useVolunteerRecruitItem.ts
Labels: 🐣 Feat

#231 feat(shelter): 봉사자 모집글 수정 페이지 진입 시, 기존 이미지 리스트 보여주는 기능 추가
  apps/shelter/src/mocks/browser.ts
  apps/shelter/src/mocks/handlers/image.ts
  apps/shelter/src/pages/volunteers/detail/_hooks/useGetVolunteerDetail.ts
  apps/shelter/src/pages/volunteers/update/index.tsx
Labels: 🐣 Feat

#236 feat: 봉사자 마이페이지에서 신청한 봉사후기 UI 및 msw 연결
  apps/volunteer/src/apis/volunteer.ts
  apps/volunteer/src/constants/applicantStatus.ts
  apps/volunteer/src/mocks/handlers/volunteer.ts
  apps/volunteer/src/pages/my/_components/ApplyRecruitments.tsx
  apps/volunteer/src/pages/my/index.tsx
  apps/volunteer/src/types/apis/volunteer.ts
Labels: 🐣 Feat, 🔥 Must have

#242 feat(shelter): 보호소 마이페이지 토글 버튼 디자인 수정 및 useMutation 사용하도록 수정
  apps/shelter/src/App.tsx
  apps/shelter/src/pages/my/_hooks/useMyPage.ts
  apps/shelter/src/pages/my/index.tsx
Labels: 🎨 Design, 🐣 Feat

#243 feat(shared): validations 전화번호 형식에 '-' 추가
  packages/shared/utils/validations.ts
Labels: 🐣 Feat, 🔥 Must have

#238 feat : 리뷰 스켈레톤
  apps/shelter/src/apis/shelter.ts
  apps/shelter/src/mocks/handlers/shelter.ts
  apps/shelter/src/pages/my/reviews/VolunteerProfile.tsx
  apps/shelter/src/pages/my/reviews/index.tsx
  packages/shared/components/ReviewItemSkeleton.tsx
  packages/shared/components/ReviewItemSkeletonList.tsx
Labels: 🐣 Feat

#244 feat : withlogin, layout 수정
  apps/shelter/src/main.tsx
  apps/volunteer/src/components/WithLogin.tsx
  apps/volunteer/src/main.tsx
  packages/shared/layout/index.tsx
Labels: 🔨 Fix

#245 feat: 봉사모집 상세페이지 보호소프로필 이동, 봉사 신청 msw 추가
  apps/volunteer/src/apis/recruitment.ts
  apps/volunteer/src/mocks/handlers/recruitment.ts
  apps/volunteer/src/pages/volunteers/detail/_hooks/useFetchRecruitmentDetail.ts
  apps/volunteer/src/pages/volunteers/detail/_hooks/useFetchSimpleShelterInfo.ts
  apps/volunteer/src/pages/volunteers/detail/_hooks/useFetchVolunteerDetail.ts
  apps/volunteer/src/pages/volunteers/detail/index.tsx
Labels: 🐣 Feat

#249 release: v0.1.3
  apps/shelter/src/App.tsx
  apps/shelter/src/apis/shelter.ts
  apps/shelter/src/main.tsx
  apps/shelter/src/mocks/browser.ts
  apps/shelter/src/mocks/handlers/image.ts
  apps/shelter/src/mocks/handlers/recruitment.ts
  apps/shelter/src/mocks/handlers/shelter.ts
  apps/shelter/src/pages/my/_hooks/useMyPage.ts
  apps/shelter/src/pages/my/index.tsx
  apps/shelter/src/pages/my/reviews/VolunteerProfile.tsx
  apps/shelter/src/pages/my/reviews/index.tsx
  apps/shelter/src/pages/volunteers/_hooks/useVolunteerRecruitItem.ts
  apps/shelter/src/pages/volunteers/detail/_hooks/useGetVolunteerDetail.ts
  apps/shelter/src/pages/volunteers/update/index.tsx
  apps/volunteer/src/apis/recruitment.ts
  apps/volunteer/src/apis/review.ts
  apps/volunteer/src/apis/volunteer.ts
  apps/volunteer/src/components/WithLogin.tsx
  apps/volunteer/src/constants/applicantStatus.ts
  apps/volunteer/src/main.tsx
  apps/volunteer/src/mocks/handlers/recruitment.ts
  apps/volunteer/src/mocks/handlers/review.ts
  apps/volunteer/src/mocks/handlers/volunteer.ts
  apps/volunteer/src/pages/my/_components/ApplyRecruitments.tsx
  apps/volunteer/src/pages/my/_components/MyReviews.tsx
  apps/volunteer/src/pages/my/index.tsx
  apps/volunteer/src/pages/shelters/reviews/update/index.tsx
  apps/volunteer/src/pages/volunteers/detail/_hooks/useFetchRecruitmentDetail.ts
  apps/volunteer/src/pages/volunteers/detail/_hooks/useFetchSimpleShelterInfo.ts
  apps/volunteer/src/pages/volunteers/detail/_hooks/useFetchVolunteerDetail.ts
  apps/volunteer/src/pages/volunteers/detail/index.tsx
  apps/volunteer/src/types/apis/review.ts
  apps/volunteer/src/types/apis/volunteer.ts
  packages/shared/components/ReviewItemSkeleton.tsx
  packages/shared/components/ReviewItemSkeletonList.tsx
  packages/shared/hooks/useUploadPhoto.ts
  packages/shared/layout/index.tsx
  packages/shared/theme/index.ts
  packages/shared/utils/validations.ts
Labels: 🔖 release
