Repository anifriends/frontend, pull requests merged in 2023-12, with the labels that each got.

#257 fix(shared, shelter, volunteer): pagination type의 pageSize, pageNumber를 size, page로 변경
  apps/shelter/src/apis/shelter.ts
  apps/shelter/src/pages/my/reviews/hooks/useFetchShelterReviews.tsx
  apps/shelter/src/pages/volunteers/_queryOptions/recruitment.ts
  apps/shelter/src/types/apis/recruitment.ts
  apps/volunteer/src/apis/volunteer.ts
  apps/volunteer/src/pages/shelters/profile/_components/ShelterReviews.tsx
  apps/volunteer/src/pages/volunteers/_queryOptions/recruitments.ts
  apps/volunteer/src/types/apis/recruitment.ts
  apps/volunteer/src/types/apis/review.ts
  packages/shared/apis/common/Recruitments.ts
  packages/shared/apis/common/Review.ts
Labels: 🔥 Must have, 🔨 Fix

#256 fix(shared): LocalErrorBoundary에서 로그인 이동 'login'에서 'signin'으로 변경
  packages/shared/components/LocalErrorBoundary.tsx
Labels: 🔥 Must have, 🔨 Fix

#262 feat(shelter, volunteer): 전화번호 형식 helperText 변경
  apps/shelter/src/pages/signup/index.tsx
  apps/volunteer/src/pages/signup/index.tsx
Labels: 🐣 Feat, 🔥 Must have

#264 feat(shared): 바텀 네비게이션 바와 헤더에 유저 인증 필요한 경우 모달창 띄우는 기능 추가
  packages/shared/components/AlertModal.tsx
  packages/shared/layout/BottomNavBar/index.tsx
  packages/shared/layout/Header/DefaultHeader/index.tsx
Labels: 🐣 Feat

#266 fix(volunteers): 봉사 모집글 아이템에 기본 이미지 추가
  apps/volunteer/src/pages/volunteers/_components/VolunteerRecruitItem.tsx
  packages/shared/assets/icon_no_image.svg
Labels: 🔨 Fix

#263 release: v0.1.4
  apps/shelter/src/apis/shelter.ts
  apps/shelter/src/pages/manage/apply/index.tsx
  apps/shelter/src/pages/my/reviews/hooks/useFetchShelterReviews.tsx
  apps/shelter/src/pages/signup/index.tsx
  apps/shelter/src/pages/volunteers/_queryOptions/recruitment.ts
  apps/shelter/src/pages/volunteers/profile/index.tsx
  apps/shelter/src/pages/volunteers/update/index.tsx
  apps/shelter/src/pages/volunteers/write/index.tsx
  apps/shelter/src/types/apis/recruitment.ts
  apps/volunteer/src/apis/recruitment.ts
  apps/volunteer/src/apis/volunteer.ts
  apps/volunteer/src/mocks/handlers/recruitment.ts
  apps/volunteer/src/pages/my/_components/MyReviews.tsx
  apps/volunteer/src/pages/my/index.tsx
  apps/volunteer/src/pages/shelters/profile/_components/ShelterReviews.tsx
  apps/volunteer/src/pages/shelters/profile/index.tsx
  apps/volunteer/src/pages/signup/index.tsx
  apps/volunteer/src/pages/volunteers/_components/VolunteerRecruitItem.tsx
  apps/volunteer/src/pages/volunteers/_queryOptions/recruitments.ts
  apps/volunteer/src/pages/volunteers/detail/_hooks/useFetchRecruitmentDetail.ts
  apps/volunteer/src/pages/volunteers/detail/index.tsx
  apps/volunteer/src/types/apis/recruitment.ts
  apps/volunteer/src/types/apis/review.ts
  packages/shared/apis/common/Recruitments.ts
  packages/shared/apis/common/Review.ts
  packages/shared/assets/icon_no_image.svg
  packages/shared/components/AlertModal.tsx
  packages/shared/components/LocalErrorBoundary.tsx
  packages/shared/layout/BottomNavBar/index.tsx
  packages/shared/layout/Header/DefaultHeader/index.tsx
Labels: 🔖 release

#270 feat: NotReady 컴포넌트 페이지 추가 및 animals, chattings 페이지에 적용
  apps/shelter/src/pages/animals/index.tsx
  apps/shelter/src/pages/chattings/index.tsx
  apps/volunteer/src/pages/animals/index.tsx
  apps/volunteer/src/pages/chattings/index.tsx
  packages/shared/components/NotReady.tsx
Labels: 🐣 Feat, 🔥 Must have

#271 feat: 로컬 스토리지에 accessToken 저장 및 자동 로그인 기능 추가
  apps/shelter/src/pages/signin/index.tsx
  apps/shelter/src/routes/index.tsx
  apps/volunteer/src/pages/signin/index.tsx
  apps/volunteer/src/routes/index.tsx
  packages/shared/components/LocalErrorBoundary.tsx
  packages/shared/components/WithLogin.tsx
  packages/shared/layout/index.tsx
  packages/shared/utils/localStorage.ts
Labels: 🐣 Feat

#273 fix: 봉사자 마이페이지의 label 상태 출석완료, 승인완료 교체
  apps/volunteer/src/constants/applicantStatus.ts
  apps/volunteer/src/pages/my/_components/ApplyRecruitments.tsx
Labels: 🔥 Must have, 🔨 Fix

#277 feat(shared): 이미지 resize util 함수 추가 및 useUploadPhoto hook 에 이미지 리사이징 기능 추가
  packages/shared/components/EditPhotoItem.tsx
  packages/shared/hooks/useUploadPhoto.ts
  packages/shared/package.json
  packages/shared/utils/image.ts
  pnpm-lock.yaml
Labels: 🐣 Feat

#276 fix: 새로고침했을때 자동 로그인이 되지 않는 버그 수정
  packages/shared/components/Loader.tsx
  packages/shared/layout/index.tsx
Labels: 🔨 Fix

#282 release: v0.1.6
  apps/shelter/src/pages/settings/account/index.tsx
  apps/shelter/src/pages/volunteers/update/index.tsx
  apps/shelter/src/pages/volunteers/write/index.tsx
  apps/volunteer/src/pages/settings/account/index.tsx
  apps/volunteer/src/pages/shelters/reviews/update/index.tsx
  apps/volunteer/src/pages/shelters/reviews/write/index.tsx
  packages/shared/components/EditPhotoItem.tsx
  packages/shared/components/Loader.tsx
  packages/shared/hooks/usePhotoUpload.ts
  packages/shared/hooks/usePhotosUpload.ts
  packages/shared/layout/index.tsx
  packages/shared/package.json
  packages/shared/utils/image.ts
  pnpm-lock.yaml
Labels: 🔖 release

#286 bug(shelter): 봉사 모집글 검색 결과 리스트 페이지에서 마감 버튼, 또는 삭제 버튼 눌러도 UI 업데이트 되지 않는 로직 수정
  apps/shelter/src/pages/volunteers/_hooks/useVolunteerRecruitItem.ts
  apps/shelter/src/pages/volunteers/index.tsx
  apps/shelter/src/pages/volunteers/search/index.tsx
Labels: 🐛 Bug

#287 feat(shelter, volunteer): 마이 페이지, 봉사 모집글 리스트 페이지에 padding-bottom 50px 추가
  apps/shelter/src/pages/my/index.tsx
  apps/shelter/src/pages/volunteers/index.tsx
  apps/volunteer/src/pages/my/index.tsx
  apps/volunteer/src/pages/volunteers/index.tsx
Labels: 🐣 Feat, 🔥 Must have

#288 feat(shelter, volunteer): 알림 페이지에 준비중(NotReady) 컴포넌트 추가
  apps/shelter/src/pages/notifications/index.tsx
  apps/volunteer/src/pages/notifications/index.tsx
Labels: 🐣 Feat, 🔥 Must have

#289 feat: 로그인 에러 상황시 toast error message 빈 값 처리, toast 중복 호출 제거
  apps/shelter/src/pages/signin/index.tsx
  apps/volunteer/src/pages/signin/index.tsx
Labels: 🐣 Feat, 🔥 Must have

#290 fix(shared): LocalErrorBoundary에서 버튼 클릭 시 error boundary 초기화 과정 추가
  packages/shared/components/LocalErrorBoundary.tsx
Labels: 🐣 Feat, 🔥 Must have

#292 fix(volunteer): 마이 페이지 MyReview 탭의 initialPageParam을 0으로 수정
  apps/volunteer/src/pages/my/_components/MyReviews.tsx
Labels: 🔥 Must have, 🔨 Fix

#295 fix : 모집글 작성 및 수정 페이지에서 시차가 나는 시간 입력되던 문제 수정
  apps/shelter/src/pages/volunteers/update/index.tsx
  apps/shelter/src/pages/volunteers/write/index.tsx
  packages/shared/utils/date.ts
Labels: 🔨 Fix

#297 fix(shelter): 봉사자 모집글 상세페이지 API 조회가 되지 않는 버그 수정
  apps/shelter/src/pages/volunteers/detail/_hooks/useGetVolunteerDetail.ts
  apps/shelter/src/pages/volunteers/detail/index.tsx
Labels: 🔨 Fix

#298 feat: 로그아웃 기능 추가
  apps/shelter/src/pages/my/index.tsx
  apps/volunteer/src/pages/settings/index.tsx
Labels: 🐣 Feat

#299 fix(common): 봉사자 및 보호소 앱의 상세 페이지에서 이미지가 없으면 캐러샐 랜더하지 않도록 수정
  apps/shelter/src/pages/volunteers/detail/index.tsx
  apps/volunteer/src/pages/volunteers/detail/index.tsx
Labels: 🐛 Bug

#302 bug(volunteer): 봉사 상세 페이지에서 비회원인 경우에는 봉사 신청 여부 API 를 요청하지 않도록 수정
  apps/volunteer/src/pages/volunteers/detail/_hooks/useFetchRecruitmentDetail.ts
  apps/volunteer/src/pages/volunteers/detail/index.tsx
  packages/shared/store/authStore.ts
Labels: 🔨 Fix

#306 fix(shelter): 마이페이지의 로그아웃 버튼 중복 제거 및 padding bottom 추가
  apps/shelter/src/pages/my/index.tsx
Labels: 🔨 Fix

#308 fix(shelter): 모집글 수정페이지에서 시간 오류 수정
  apps/shelter/src/pages/volunteers/update/index.tsx
Labels: 🔨 Fix

#310 release: v0.1.8
  apps/shelter/src/pages/my/index.tsx
  apps/shelter/src/pages/settings/account/index.tsx
  apps/shelter/src/pages/volunteers/detail/index.tsx
  apps/shelter/src/pages/volunteers/update/index.tsx
Labels: 🔖 release

#312 fix(volunteer): 마이 페이지 탭들 내부 useSusepnseInfiniteQuery의 initialPageParam을 0으로 수정
  apps/volunteer/src/pages/shelters/profile/_components/ShelterRecruitments.tsx
  apps/volunteer/src/pages/shelters/profile/_components/ShelterReviews.tsx
Labels: 🔥 Must have, 🔨 Fix

#316 release: v0.1.9
  apps/volunteer/src/pages/shelters/profile/_components/ShelterRecruitments.tsx
  apps/volunteer/src/pages/shelters/profile/_components/ShelterReviews.tsx
Labels: 🔖 release

#317 feat: toast 알림 추가, bug 봉사자앱 계정정보수정 imageUrl { } 로 요청 수정
  apps/shelter/src/pages/settings/account/index.tsx
  apps/shelter/src/pages/volunteers/detail/index.tsx
  apps/volunteer/src/apis/volunteer.ts
  apps/volunteer/src/pages/my/_components/MyReviews.tsx
  apps/volunteer/src/pages/my/index.tsx
  apps/volunteer/src/pages/settings/account/index.tsx
  apps/volunteer/src/pages/volunteers/detail/_hooks/useFetchRecruitmentDetail.ts
Labels: 🐣 Feat, 🐛 Bug

#320 feat: Tabs 컴포넌트 route replace true로 설정
  packages/shared/components/Tabs.tsx
Labels: 🐣 Feat, 💧 Should have

#325 feat(shared): updateToast util 함수 추가
  packages/shared/utils/toast.ts
Labels: 🐣 Feat, 💧 Should have

#326 refactor(shelter, volunteer): signup 페이지 내부 toast updateToast로 변경
  apps/shelter/src/pages/signup/index.tsx
  apps/volunteer/src/pages/signup/index.tsx
Labels: 💧 Should have, 🛠 Refactor

#328 refactor(shelter, volunteer): signin 페이지 내부 toast updateToast로 변경
  apps/shelter/src/pages/signin/index.tsx
  apps/volunteer/src/pages/signin/index.tsx
Labels: 💧 Should have, 🛠 Refactor

#330 feat: 봉사자 신청현황 페이지 toast updatToast로 변경, onError 추가, toast 설명 폰트 속성 변경
  apps/shelter/src/mocks/handlers/recruitment.ts
  apps/shelter/src/pages/manage/apply/_components/ManageApplyItem.tsx
Labels: 🐣 Feat, 💧 Should have, 🛠 Refactor

#332 feat(shelter): 봉사자 신청 현황 페이지 신청된 상태가 같을 경우 서버 호출 제거
  apps/shelter/src/pages/manage/apply/_components/ManageApplyItem.tsx
Labels: 🐣 Feat, 💧 Should have

#335 chore(shelter, volunteer): @lukemorales/query-key-factory 삭제
  apps/shelter/package.json
  apps/volunteer/package.json
  pnpm-lock.yaml
Labels: 🏅 Chore

#337 feat: 봉사자 출석 관리 페이지 디자인 모바일에서 웹까지 확장
  apps/shelter/src/mocks/handlers/manage.ts
  apps/shelter/src/pages/manage/attendance/index.tsx
Labels: 🐣 Feat, 🔥 Must have

#339 feat: 보호소, 봉사자 앱 title, icon 변경
  apps/shelter/index.html
  apps/shelter/public/favicon.ico
  apps/volunteer/index.html
  apps/volunteer/public/favicon.ico
Labels: 🐣 Feat, 🔥 Must have
